export const product = [
  {
    image: require('../../../assets/G1.png'),
    shown: [
      {
        name: 'white Label',
        companyname: 'Parrys',
        quantity: '1kg',
        price: 60,
        id: 71,
        image: require('../../../assets/image1.png'),
      },
      {
        name: 'Potato',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
        id: 72,
        image: require('../../../assets/image2.png'),
      },
      {
        name: 'Ashirwad aata',
        companyname: 'Ashirwad',
        quantity: '10kg',
        price: 360,
        id: 73,
        image: require('../../../assets/image1.png'),
      },
      {
        name: 'Raw - Banana',
        companyname: 'Rk bazar',
        quantity: '10 pcs',
        price: 360,
        id: 74,
        image: require('../../../assets/image5.png'),
      },
      {
        name: 'Bread',
        companyname: 'Rkbazaar',
        quantity: '10 pcs',
        price: 660,
        id: 75,
        image: require('../../../assets/image4.png'),
      },
    ],
  },
  {
    image: require('../../../assets/G2.png'),
    shown: [
      {
        name: 'white Label',
        companyname: 'Parrys',
        quantity: '1kg',
        price: 60,
        id: 76,
        image: require('../../../assets/image5.png'),
      },
      {
        name: 'Potato',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
        id: 77,
        image: require('../../../assets/image4.png'),
      },
      {
        name: 'Ashirwad aata',
        companyname: 'Ashirwad',
        quantity: '10kg',
        price: 360,
        id: 78,
        image: require('../../../assets/image3.png'),
      },
      {
        name: 'Raw - Banana',
        companyname: 'Rk bazar',
        quantity: '10 pcs',
        price: 360,
        id: 79,
        image: require('../../../assets/image2.png'),
      },
      {
        name: 'Bread',
        companyname: 'Rkbazaar',
        quantity: '10 pcs',
        price: 660,
        id: 80,
        image: require('../../../assets/image1.png'),
      },
    ],
  },
  {
    image: require('../../../assets/G1.png'),
    shown: [
      {
        name: 'white Label',
        companyname: 'Parrys',
        quantity: '1kg',
        id: 82,
        price: 60,
        image: require('../../../assets/image1.png'),
      },
      {
        name: 'Potato',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
        id: 83,
        image: require('../../../assets/image2.png'),
      },
      {
        name: 'Ashirwad aata',
        companyname: 'Ashirwad',
        quantity: '10kg',
        price: 360,
        image: require('../../../assets/image1.png'),
      },
      {
        name: 'Raw - Banana',
        companyname: 'Rk bazar',
        quantity: '10 pcs',
        price: 360,
        id: 84,
        image: require('../../../assets/image5.png'),
      },
      {
        name: 'Bread',
        companyname: 'Rkbazaar',
        quantity: '10 pcs',
        price: 660,
        id: 85,
        image: require('../../../assets/image4.png'),
      },
    ],
  },
  {
    image: require('../../../assets/G1.png'),
    shown: [
      {
        name: 'white Label',
        companyname: 'Parrys',
        quantity: '1kg',
        price: 60,
        id: 86,
        image: require('../../../assets/image1.png'),
      },
      {
        name: 'Potato',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
        id: 88,
        image: require('../../../assets/image2.png'),
      },
      {
        name: 'Ashirwad aata',
        companyname: 'Ashirwad',
        quantity: '10kg',
        price: 360,
        id: 89,
        image: require('../../../assets/image1.png'),
      },
      {
        name: 'Raw - Banana',
        companyname: 'Rk bazar',
        quantity: '10 pcs',
        price: 360,
        id: 90,
        image: require('../../../assets/image5.png'),
      },
      {
        name: 'Bread',
        companyname: 'Rkbazaar',
        quantity: '10 pcs',
        price: 660,
        id: 91,
        image: require('../../../assets/image4.png'),
      },
    ],
  },
  {
    image: require('../../../assets/G1.png'),
    shown: [
      {
        name: 'white Label',
        companyname: 'Parrys',
        quantity: '1kg',
        price: 60,
        id: 92,
        image: require('../../../assets/image1.png'),
      },
      {
        name: 'Potato',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
        id: 93,
        image: require('../../../assets/image2.png'),
      },
      {
        name: 'Ashirwad aata',
        companyname: 'Ashirwad',
        quantity: '10kg',
        price: 360,
        id: 94,
        image: require('../../../assets/image1.png'),
      },
      {
        name: 'Raw - Banana',
        companyname: 'Rk bazar',
        quantity: '10 pcs',
        price: 360,
        id: 95,
        image: require('../../../assets/image5.png'),
      },
      {
        name: 'Bread',
        companyname: 'Rkbazaar',
        quantity: '10 pcs',
        price: 660,
        id: 96,
        image: require('../../../assets/image4.png'),
      },
    ],
  },
];
