/* eslint-disable prettier/prettier */
export const ROUTES = {
  HOME: 'HOME',
  SPLASH: 'SPLASH',
  DASHBOARD: 'DASHBOARD',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  PRODUCTPAGE: 'PRODUCTPAGE',
  BASKET: 'BASKET',
  REVIEW: 'REVIEW',
  PRODUCTDESCRIPTION: 'PRODUCTDESCRIPTION',
  PAYMENTSCREEN: 'PAYMENTSCREEN',
};
