export const orderagain = [
  {
    id: 11,
    name: 'White Label',
    companyname: 'Parrys',
    quantity: '1kg',
    price: 60,
    image: require('../../../assets/image1.png'),
  },
  {
    id: 12,
    name: 'Potato',
    companyname: 'Rk bazaar',
    quantity: '1kg',
    price: 360,
    image: require('../../../assets/image2.png'),
  },
  {
    id: 13,
    name: 'Ashirwad aata',
    companyname: 'Ashirwad',
    quantity: '10kg',
    price: 360,
    image: require('../../../assets/image1.png'),
  },
  {
    id: 14,
    name: 'Raw - Banana',
    companyname: 'Rk bazar',
    quantity: '10 pcs',
    price: 360,
    image: require('../../../assets/image5.png'),
  },
  {
    id: 15,
    name: 'Bread',
    companyname: 'Rkbazaar',
    quantity: '10 pcs',
    price: 660,
    image: require('../../../assets/image4.png'),
  },
];
