export const vegetableandfruits = [
  {
    name: 'Vegetables & Fruits',
    quantity: 220,
    image: require('../../../assets/image1.png'),
    block: [
      {
        id: 41,
        image: require('../../../assets/image1.png'),
        name: 'Aata',
        companyname: 'Ashirwad',
        quantity: '10kg',
        price: 400,
      },
      {
        id: 42,
        image: require('../../../assets/image2.png'),
        name: 'Potato',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
      },
      {
        id: 43,
        image: require('../../../assets/image3.png'),
        name: 'Eggs',
        companyname: 'Rk bazaar ',
        quantity: '1kg',
        price: 360,
      },
      {
        id: 44,
        image: require('../../../assets/image4.png'),
        name: 'Bread',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
      },
    ],
  },

  {
    name: 'Atta,Rice & Oil',
    quantity: 220,
    image: require('../../../assets/image2.png'),
    block: [
      {
        id: 45,
        image: require('../../../assets/image1.png'),
        name: 'Aata',
        companyname: 'Ashirwad',
        quantity: '1kg',
        price: 360,
      },
      {
        id: 46,
        image: require('../../../assets/image2.png'),
        name: 'Potato',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
      },
      {
        id: 47,
        image: require('../../../assets/image3.png'),
        name: 'Eggs',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
      },
      {
        id: 48,
        image: require('../../../assets/image4.png'),
        name: 'Bread',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
      },
    ],
  },
  {
    name: 'Dry fruits',
    quantity: 220,
    image: require('../../../assets/image3.png'),
    block: [
      {
        id: 49,
        image: require('../../../assets/image1.png'),
        name: 'Aata',
        companyname: 'Ashirwad',
        quantity: '10kg',
        price: 400,
      },
      {
        id: 50,
        image: require('../../../assets/image2.png'),
        name: 'Potato',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
      },
      {
        id: 51,
        image: require('../../../assets/image3.png'),
        name: 'Eggs',
        companyname: 'Rk bazaar ',
        quantity: '1kg',
        price: 360,
      },
      {
        id: 52,
        image: require('../../../assets/image4.png'),
        name: 'Bread',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
      },
    ],
  },
  {
    name: 'Deos & Perfumes',
    quantity: 220,
    image: require('../../../assets/image4.png'),
    block: [
      {
        id: 53,
        image: require('../../../assets/image1.png'),
        name: 'Aata',
        companyname: 'Ashirwad',
        quantity: '10kg',
        price: 400,
      },
      {
        id: 54,
        image: require('../../../assets/image2.png'),
        name: 'Potato',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
      },
      {
        id: 55,
        image: require('../../../assets/image3.png'),
        name: 'Eggs',
        companyname: 'Rk bazaar ',
        quantity: '1kg',
        price: 360,
      },
      {
        id: 56,
        image: require('../../../assets/image4.png'),
        name: 'Bread',
        companyname: 'Rk bazaar',
        quantity: '1kg',
        price: 360,
      },
    ],
  },
];
